version: '3.7'
services:
  database:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=88888888
      - MONGO_INITDB_DATABASE=sampledb
      - MONGO_INITDB_USERNAME=sampledb
      - MONGO_INITDB_PASSWORD=12345678
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./db:/data/db
